<a href="https://colab.research.google.com/github/wsj20010128/ML_Notes/blob/main/02_kNN_in_scikit_learn/02_kNN_in_scikit_learn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import matplotlib.pyplot as plt

# raw_data_X: features
raw_data_X = [[3.393533211, 2.331273381],
        [3.110073483, 1.781539638],
        [1.343808831, 3.368360954],
        [3.582294042, 4.679179110],
        [2.280362439, 2.866990263],
        [7.423436942, 4.696522875],
        [5.745051997, 3.533989803],
        [9.172168622, 2.511101045],
        [7.792783481, 3.424088941],
        [7.939820817, 0.791637231]] 
        
# raw_data_y: labels
# 0 -> benign
# 1 -> malignant
raw_data_y = [0, 0, 0, 0, 0, 1, 1, 1, 1, 1]

X_train = np.array(raw_data_X)
y_train = np.array(raw_data_y)

# a new sample
x = np.array([8.093607318, 3.365731514])

In [4]:
%run kNN_function/kNN.py

In [6]:
predict_y = kNN_classify(6, X_train, y_train, x)
predict_y

1

## kNN in scikit-learn

In [7]:
from sklearn.neighbors import KNeighborsClassifier

In [13]:
kNN_classifier = KNeighborsClassifier(n_neighbors=6)

In [14]:
kNN_classifier.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=6)

In [17]:
X_predict = x.reshape(1, -1)
X_predict

array([[8.09360732, 3.36573151]])

In [19]:
y_predict = kNN_classifier.predict(X_predict)
y_predict

array([1])

In [20]:
y_predict[0]

1

## Rearrange the codes of kNN

In [26]:
%run kNN/kNN.py

In [27]:
knn_clf = KNNClassifier(k=6)

In [28]:
knn_clf.fit(X_train, y_train)

KNN(k=6)

In [30]:
y_predict = knn_clf.predict(X_predict)
y_predict

array([1])

In [31]:
y_predict[0]

1