<a href="https://colab.research.google.com/github/wsj20010128/ML_Notes/blob/main/Gradient-Descent/06-Debug-Gradient/06-Debug-Gradient.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Debug Gradient

In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
np.random.seed(666)
X =np.random.random(size=(1000, 10))

In [3]:
true_theta = np.arange(1, 12, dtype=float)

In [5]:
X_b = np.hstack([np.ones((len(X), 1)), X])
y = X_b.dot(true_theta) + np.random.normal(size=1000)

In [6]:
X.shape

(1000, 10)

In [7]:
y.shape

(1000,)

In [8]:
true_theta

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [9]:
def J(theta, X_b, y):
  try:
      return np.sum((y - X_b.dot(theta))**2) / len(X_b)
  except:
      return float('inf')

In [10]:
def dJ_math(theta, X_b, y):
  return X_b.T.dot(X_b.dot(theta) - y) * 2. / len(y)

In [12]:
def dJ_debug(theta, X_b, y, epsilon=0.01):
  res = np.empty(len(theta))
  for i in range(len(theta)):
    theta_1 = theta.copy()
    theta_1[i] += epsilon
    theta_2 = theta.copy()
    theta_2[i] -= epsilon
    res[i] = (J(theta_1, X_b, y) - J(theta_2, X_b, y)) / (2 * epsilon)
  return res

In [13]:
def gradient_descent(dJ, X_b, y, initial_theta, eta, n_iters = 1e4, epsilon=1e-8):
    
  theta = initial_theta
  cur_iter = 0

  while cur_iter < n_iters:
      gradient = dJ(theta, X_b, y)
      last_theta = theta
      theta = theta - eta * gradient
      if(abs(J(theta, X_b, y) - J(last_theta, X_b, y)) < epsilon):
          break
            
      cur_iter += 1

  return theta

In [14]:
X_b = np.hstack([np.ones((len(X), 1)), X])
initial_theta = np.zeros(X_b.shape[1])
eta = 0.01

%time theta = gradient_descent(dJ_debug, X_b, y, initial_theta, eta)
theta

CPU times: user 6.44 s, sys: 4.54 s, total: 11 s
Wall time: 5.62 s


array([ 1.1251597 ,  2.05312521,  2.91522497,  4.11895968,  5.05002117,
        5.90494046,  6.97383745,  8.00088367,  8.86213468,  9.98608331,
       10.90529198])

In [15]:
%time theta = gradient_descent(dJ_math, X_b, y, initial_theta, eta)
theta

CPU times: user 841 ms, sys: 502 ms, total: 1.34 s
Wall time: 703 ms


array([ 1.1251597 ,  2.05312521,  2.91522497,  4.11895968,  5.05002117,
        5.90494046,  6.97383745,  8.00088367,  8.86213468,  9.98608331,
       10.90529198])